spring.application.name=payment
#spring.datasource.url=jdbc:postgresql://db:5432/pismo
spring.datasource.url=jdbc:postgresql://localhost:5432/pismo
spring.datasource.username=postgres
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=memory

